# -*- coding: utf-8 -*-
import os
import json
import requests
import feedparser
from facebook_scraper import get_posts

# 設定
JSON_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '../src/data/news.json')
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

FACEBOOK_PAGES = [
    {"name": "Lao Pháttháná Lpf", "id": "LaoPhathanaNews"},
    {"name": "Tholakhong", "id": "tholakhong"},
    {"name": "Laopost", "id": "laopost"},
    {"name": "KPL Lao News Agency", "id": "kplnews"}
]

def fetch_facebook_news():
    raw_posts = []
    print("Fetching Facebook posts...")
    for page in FACEBOOK_PAGES:
        try:
            # 最新の3件の投稿を取得
            for post in get_posts(page["id"], pages=1):
                if post.get("text"):
                    raw_posts.append({
                        "source": page["name"],
                        "text": post["text"][:1000], # 制限付き長さを切り出す
                        "date": str(post.get("time")),
                        "url": post.get("post_url") or f"https://facebook.com/{page['id']}"
                    })
        except Exception as e:
            print(f"Failed to fetch posts from {page['name']}: {e}")
    return raw_posts

def fetch_rss_news():
    raw_news = []
    # KPL Web RSS (例)
    print("Fetching RSS feeds...")
    kpl_rss = "http://kpl.gov.la/EN/rss.aspx"
    try:
        feed = feedparser.parse(kpl_rss)
        for entry in feed.entries[:5]:
            raw_news.append({
                "source": "Lao News Agency (KPL)",
                "text": f"{entry.title}\n{entry.description}",
                "date": entry.get("published", ""),
                "url": entry.link
            })
    except Exception as e:
        print(f"Failed to fetch KPL RSS: {e}")
        
    return raw_news

def generate_articles_via_gemini(raw_data):
    if not GEMINI_API_KEY:
        print("GEMINI_API_KEY not found. Skipping API generation.")
        return []
        
    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": GEMINI_API_KEY
    }
    
    # ハルシネーションを防ぎ、正確なメタデータを維持するためのプロンプト指示
    prompt_instruction = f"""
あなたはラオスのニュースポータルサイトの優秀な日本語編集者です。
入力された生のニュース情報から、信頼性の高い、ハルシネーションのない日本語の要約記事を生成してください。

【厳格な指示】
1. 各記事について、提供された元のソースデータに存在する「source（情報源メディア名）」「url（リンク）」を絶対に偽造せず、そのまま出力JSONに含めること。
2. 記事のタイトル・本文は正確に要約翻訳し、存在しない事実を捏造しないこと。
3. 出力する記事数は、入力データの中で最も重要かつ注目度の高いトピックを **「3〜5件」** に厳密に絞り込んでください。
4. 出力は以下の構造のJSON配列のみを返してください。不要なMarkdown囲み（```json等）は一切含めないでください。

JSON構造の定義:
[
  {
    "id": "auto-uuid",
    "category": "経済" または "社会" または "国際" または "観光",
    "title": "日本語のタイトル",
    "summary": "1〜2文程度の簡潔な概要",
    "date": "YYYY-MM-DD形式",
    "readTime": "3 min read"などの推測時間,
    "source": "提供された元のメディア名",
    "picksCount": 0,
    "viewsCount": 0,
    "image": "",
    "takeaways": [
      "重要なポイント1",
      "重要なポイント2",
      "重要なポイント3"
    ],
    "content": "# 本文のタイトル\\n本文詳細（Markdown形式。**太字**や*リスト*などを適度に使用）"
  }}
]

入力データ:
{json.dumps(raw_data, ensure_ascii=False, indent=2)}
"""

    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent"
    payload = {
        "contents": [{"parts": [{"text": prompt_instruction}]}]
    }
    
    try:
        res = requests.post(url, headers=headers, json=payload)
        res_json = res.json()
        output_text = res_json['candidates'][0]['content']['parts'][0]['text'].strip()
        
        # 不要なMarkdownマーカーをクリーンアップ
        if output_text.startswith("```"):
            output_text = output_text.split("```")[1]
            if output_text.startswith("json"):
                output_text = output_text[4:]
        
        generated_articles = json.loads(output_text.strip())
        return generated_articles
    except Exception as e:
        print(f"Gemini API invocation failed: {e}")
        return []

def main():
    fb_news = fetch_facebook_news()
    rss_news = fetch_rss_news()
    all_raw = fb_news + rss_news
    
    if not all_raw:
        print("No raw data collected.")
        return
        
    new_articles = generate_articles_via_gemini(all_raw)
    if not new_articles:
        print("No articles generated by LLM.")
        return

    # 既存のJSONファイルを読み込んでマージ
    if os.path.exists(JSON_PATH):
        try:
            with open(JSON_PATH, 'r', encoding='utf-8') as f:
                existing_data = json.load(f)
        except Exception:
            existing_data = []
    else:
        existing_data = []
        
    existing_ids = {art["id"] for art in existing_data}
    
    merged_data = []
    # 新しい記事を追加（ID重複防止）
    for art in new_articles:
        if art["id"] not in existing_ids:
            merged_data.append(art)
            
    # 古い記事を結合
    merged_data.extend(existing_data)
    
    # 保存
    with open(JSON_PATH, 'w', encoding='utf-8') as f:
        json.dump(merged_data, f, ensure_ascii=False, indent=2)
        
    print(f"Pipeline finished. Added {len(new_articles)} new articles successfully.")

if __name__ == '__main__':
    main()
